### ISSUE TITLE
Falling through floor

### ISSUE THREAD

**Issue by edvardodegaard** [BeardScript/RogueFPSExample#1]
Loading the project from Github and into RogueEngine (as described in readme.md) and hitting Play makes me fall through the floor instantly. 

Expected behaviour: Clicking play should give the same experience as on the example website with the game. It works fine there.

Clicking the localhost link gives the same issue as the in-engine preview screen.

MacOS 11.6, node v14.17.5.

**Comment by BeardScript** [comment]
Hi @camelgod, sorry I missed your report here. I've finally found time to update old projects. Thanks for reporting this issue, it's fixed now!
